import time
import easygopigo3 as easy
my_gopigo = easy.EasyGoPiGo3()

my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
time.sleep(1)
my_gopigo.turn_degrees(180)
my_gopigo.drive_inches(8)
time.sleep(1)

my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
time.sleep(1)
my_gopigo.drive_inches(8)
time.sleep(1)

my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
time.sleep(1)
my_gopigo.turn_degrees(60)
my_gopigo.drive_inches(8)
time.sleep(1)

my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
time.sleep(1)
my_gopigo.drive_inches(8)
time.sleep(1)

my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
time.sleep(1)
my_gopigo.drive_inches(8)
time.sleep(1)

my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
time.sleep(1)
my_gopigo.turn_degrees(90)
my_gopigo.drive_inches(8)
time.sleep(1)

my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
time.sleep(1)
my_gopigo.turn_degrees(20)
my_gopigo.drive_inches(8)
time.sleep(1)

my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
time.sleep(1)
my_gopigo.turn_degrees(90)
my_gopigo.drive_inches(8)
time.sleep(1)

my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
my_gopigo.turn_degrees(360)
